[package]
name = "graphics_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.37.0+1.3.209"
winit = "0.27.2"
vk-shader-macros = "0.2.8"
gpu-allocator = "0.20.0"
nalgebra = "0.31.3"